### ISSUE TITLE
Timezone coming from browser; Timestamp is coming from server

### ISSUE THREAD

**Issue by xdaxdb** [ytti/oxidized-web#107]
I notice that the time displayed on the updates is the server time, in my case UTC. But the time zone is being pulled from the browser. So the time is going to be wrong for anyone looking at the page from a different timezone than the server.

Suggestion for quick fix: Just pull the timezone from the server and don't bother trying to convert the time  for the browser. Good 'nuf.

**Comment by ytti** [comment]
I don't like the wording ```wrong```, unless I misunderstood you. Because if I understood you correctly, you're saying all clocks not in UTC time are wrong.

We used to work like you want, because we store all times in UTC regardless what your server time is, some people didn't like this. They wanted local time, and I'm not going to store anything in non UTC, but I'm happy to do presentation in non UTC.

I think only reasonable fix here is configurable TZ in the UI side. Default to local time, allow people to change the presentation TZ to what ever they want.

**Comment by xdaxdb** [comment]
To clarify: I prefer UTC also. The time on my server is UTC. The time
displayed on the webUI is the correct time (in UTC). But the timestamp says
"PDT" which I assume is coming from the browsers because local time here is
PDT. But the time being displayed is the correct UTC time.

**Comment by ytti** [comment]
Oh right. It definitely should be converted to local timezone by the code. 

But hopefully in future we can also allow user to change the display timezone to UTC, or specific offset of it.

**Comment by xdaxdb** [comment]
In the most recent version the problem no longer exists. Installed 2 days ago.

**Comment by ytti** [comment]
Thanks.
