### ISSUE TITLE
Config displayed incorrectly

### ISSUE THREAD

**Issue by roedie** [ytti/oxidized-web#132]
Hi,

I've upgraded to  0.9.0 from 0.8.0. Now when I want to look at a config from a couple of changes ago the HTML is a bit mixed up. " is displayed as &quote; and all the newlines are double newlines.

If I look at diffs the same happens.

Looking at the last config directly from the main page is working fine.

Regards,

Sander

**Comment by hestonk** [comment]
@roedie i believe #116 broke this. I those changes on this file and everything looks normal now. I'm very unfamiliar with Ruby and HAML but I think i should be able to reverse engineer and fix this.

**Comment by hestonk** [comment]
Figured it out.....Created #135 to fix this.

**Comment by roedie** [comment]
Just tested this, and it fixes it indeed.

**Comment by roedie** [comment]
Hmmm, no, it doesn't fix it completely. When I go to diff screen, and then select a full config of a specific version I still get the &quote.

**Comment by hestonk** [comment]
@roedie yes that is hard-coded in the ruby file. I was experimenting with changing it. We should probably ask @ytti whether a blank space (which I think is the intention of &nbsp; is) is valid. I think &nbsp; within a <div> tag itself is always going to display. Really it should be a <br /> but due to HAML its harder to do that (at least that's what i think.
Also, if you have &'s within your code, they will be displayed as &amp;. I'm not sure `:escaped` is really necessary.

**Comment by candlerb** [comment]
I think there are two issues:

* Spacing with `white-space: pre` https://github.com/ytti/oxidized/issues/924
* Escaping of HTML entities https://github.com/ytti/oxidized/issues/925

(Those issues now closed because I had opened them in the wrong repository, sorry about that)

**Comment by FlorianB06** [comment]
Hi,
any update or fix on this issue ?
Thank you
