### ISSUE TITLE
pfsense 

### ISSUE THREAD

**Issue by jorhardware** [ytti/oxidized-web#133]
Hi, @ytti 
i use oxidized for backup configuration of my pfsense and it works, very nice, except for versions with git output, the code is line spaces white.

Here are screenshots to illustrate the problem:

- with the "configuration" button from first page, no problem:
http://imageshack.com/a/img922/9202/wvnLmy.jpg

- with the versions button then configuration, the code is spaces line white, for pfsense backup, for another devices, it’s fine! Here problem:
http://imagizer.imageshack.us/a/img922/976/eeCucR.jpg

This update https://github.com/ytti/oxidized-web/pull/116, it's applied!
 
can you provide a solution or fix the problem ? thanks

**Comment by OCangrand** [comment]
Hi,

It seems the problem come from the `:escaped` string from haml files in /var/lib/gems/.../oxidized-web-0.9.1/lib/oxidized/web/views/version.haml and diffs.haml.

You have to delete the `:escaped` string like this :
from :
```
%div>
    :escaped
        #{line}
```
to :
```
%div> #{line}
```
This is for version.haml, you have to do the same for all the `:escaped` string in diffs.haml (there are at the end of the file)
This is only a local fix so the problem persists since those files are generated by gem.
