### ISSUE TITLE
CRUD Interface

### ISSUE THREAD

**Issue by NatalNW** [ytti/oxidized-web#199]
Why oxidized-web has not an interface to add, delete or edit a node saved on database?

**Comment by ytti** [comment]
I think the simple answer is, because no one wrote it. But my answer is, I wouldn't even want it, I don't see Oxidized in centre of your orchestration, I don't see it as your source of truth, I see Oxidized as consumer of your source of truth. 
So Oxidized has very good support of consuming arbitrary sources, where ever your truth may be, we should be able to support it. 

There are quite many requirements for good source of truth, with few synergies with Oxidized.

**Comment by NatalNW** [comment]
First, Thanks for the quick answer!

You wanna mean oxidized have to be used only as backup tool. And to management of nodes has to be done through some source of truth. So this make oxidized confident to be used.

**Comment by ytti** [comment]
Yes. I mean you have tons of tolls for network, provisioning, monitoring, configuration backups, statistics etc. All of these need information about what devices you have, and all of these should consult same single source of truth. So you add device to one place, and every system knows about it. This is what we try to support well.

**Comment by NatalNW** [comment]
Yes, of course, that's make sense. With a source of truth I'll be able to do a central point of management about my devices.
Could I use a tool to be my source of truth, like phpIPAM or NetBox?

**Comment by ytti** [comment]
I'm not comfortable giving recommendation, I've always used something homegrown. What is right for given company/network depends lot on the constrains they currently have, what is realistic what is unrealistic. 
What I view as right way to do things may be unrealistic given practical constrains companies have due to cultural or legacy reasons.

**Comment by NatalNW** [comment]
I understand your point about the companies. A tool builded homegrown will attend better the needs of each company, but, on other hands, open source projects may be adapted given constraints they have.
